version: "3.8"
services:
  master:
    image: redis:alpine
    container_name: master
    ports:
      - 6379

  slave:
    image: redis:alpine
    command: redis-server --replicaof master 6379
    depends_on:
      - master

  sentinel:
    build: .
    command: redis-server /usr/local/etc/redis/sentinel.conf --sentinel
    depends_on:
      - master
      - slave
