version: "3.8"
services:
  redis-master:
    image: redis:alpine
    networks:
      hostnet: {}

  redis-slave:
    image: redis:alpine
    networks:
      hostnet: {}
    command: redis-server --port 6380 --replicaof redis-master 6379

  sentinel-5000:
    image: redis:alpine
    networks:
      hostnet: {}
    volumes:
      - "./sentinel-5000.conf:/data/sentinel-5000.conf"
    command: redis-server /data/sentinel-5000.conf --sentinel

  sentinel-5001:
    image: redis:alpine
    networks:
      hostnet: {}
    volumes:
      - "./sentinel-5001.conf:/data/sentinel-5001.conf"
    command: redis-server /data/sentinel-5001.conf --sentinel

  sentinel-5002:
    image: redis:alpine
    networks:
      hostnet: {}
    volumes:
      - "./sentinel-5002.conf:/data/sentinel-5002.conf"
    command: redis-server /data/sentinel-5002.conf --sentinel

networks:
  hostnet:
    driver: bridge